from connector import create_connection

# establish connection with database
connection = create_connection("./compcon.db")

cursor = connection.cursor()


# table creation

# pilot equipment. includes weapons, armor, misc gear
create_pilotweapons = """CREATE TABLE IF NOT EXISTS PilotWeapons(
                       description text,
                       tags text,
                       range integer,
                       threat integer,
                       damage text,
                       damagetype text)"""

create_hardsuits = """CREATE TABLE IF NOT EXISTS Hardsuits(
                      type text,
                      bonuses text,
                      armor integer,
                      evasion integer,
                      edefense integer,
                      speed integer)"""

create_pilotmiscgear = """CREATE TABLE IF NOT EXISTS MiscGear(
                      name text,
                      description text)"""

cursor.execute(create_pilotweapons)
cursor.execute(create_hardsuits)
cursor.execute(create_pilotmiscgear)

load_pilotweapons = """INSERT INTO PilotWeapons(
                       description,tags,range,threat,damage,damagetype)
                       VALUES
                       ("Melee","Archaic",0,1,1,"Kinetic"),
                       ("Melee","Archaic",5,0,1,"Kinetic"),
                       ("Light A/C","Sidearm",0,1,1,"Kinetic"),
                       ("Medium A/C","",0,1,2,"Kinetic"),
                       ("Heavy A/C","Inaccurate",0,1,3,"Kinetic"),
                       ("Light Signature","Sidearm",3,0,1,"Variable"),
                       ("Medium Signature","",5,0,2,"Variable"),
                       ("Heavy Signature","Ordnance, Loading",10,0,4,"Variable")"""
cursor.execute(load_pilotweapons)

load_hardsuits = """INSERT INTO Hardsuits(
                    type,bonuses,armor,evasion,edefense,speed)
                    VALUES
                    ("Light","+3 HP",0,10,10,4),
                    ("Assault","+3 HP",1,8,8,4),
                    ("Heavy","+3 HP",2,6,8,3),
                    ("Mobility","Flight",0,10,10,5),
                    ("Stealth","Invisibility",0,8,8,4)"""
cursor.execute(load_hardsuits)

load_pilotmiscgear = """INSERT INTO MiscGear(name,ammo,action,description,)
                    VALUES
("Antiphoton Visor","Designed to protect the wearer’s eyes from intense bursts of light, antiphoton visors are commonly found among breach teams and solar-forward operators. They are effective against flash weapons, intense UV light, and incidental charges from energy weapons."),
("Camo Cloth","A square of reactive material that slowly shifts to reflect the surrounding environment, enough to cover a human comfortably. The transition takes about 10 seconds and makes anything hidden underneath very difficult to spot."),
("Dataplating","Dataplating is a general term for any comm-linked jewelry, subdermal netting, wearable jaw, brow, or maxillary plates, etc., that allows subvocal communication and persistent heads-up and augmented reality displays without wearing a helm. Dataplates can quickly translate nearly any language, and allow users to communicate with each other all but silently."),
("Extra Rations","Pilot rations aren’t much better than their nautical forerunners – both are variants on hardtack and nutrient paste. Pilots often carry a stash of extra food, or luxuries like chocolate, coffee, alcohol, or preserved goods from their homeworld. These rations can be used to barter or boost morale."),
("Flexsuit","A strong base-layer suit that recycles water, generates nutrients, and adapts very rapidly to hostile environs, maintaining a stable condition and extending survivability. Flexsuit wearers can go for roughly a week without eating or drink thanks to the ambrosia paste generated by their suit before its systems are depleted; however, they don’t prevent feelings of hunger. Removing the suit for a day or two is enough to replenish its reserves. Flexsuits also maintain a steady temperature within acceptable parameters."),
("Handheld Printer","A miniaturized version of Union’s full-scale printers, handheld printers can be used to make simple objects out of flexible and durable plastic – as long as you have the right pattern chip."),
("Subjectivity-Enhancement Suite","A subjectivity-enhancement suite is a set of cybernetic implants allowing users to hack systems without a rig. Users of these suites blend the organic with the synthetic, gaining the ability to extrude implanted universal-plug cables from within their body to make hardline connections with terminals. When plugged in, users can access a comprehensive, fully interactive alternate-reality interface with direct omninet access, making navigating – or hacking – local and networked systems as easy as wishing it so (of course, you must be careful: by opening up your mind to the digital, you may face dangers other, less enhanced people are ignorant of)."),
("Infoskin","A reactive, synthetic polymer with advanced qualities, infoskin bonds quickly to real skin and hair. Once applied, it responds to electronic signals delivered by linked software, rapidly changing its color and texture – even contorting and distorting its form – allowing wearers to make minor changes to their appearance. With infoskin, it’s a simple matter to alter facial features, hair color, or makeup patterns."),
("Mag-Clamps","These clamps attach easily to any metal surface, enhancing maneuverability in zero-g environments or when repairing mechs. They can be carried or fitted to boots."),
("Nanite Spray","A spray paint that can be applied to any surface. Nanite spray is invisible to the naked eye but able to transmit simple messages or small data packets when scanned."),
("Omnihook","A portable – if bulky – omninet terminal that allows for communication, data transfer, and limited hotspotting. Omnihooks are extremely valuable, although most mech squads have at least one. Tuning an omnihook requires a high level of skill, so they are usually mounted or carried by designated operators."),
("Personal Drone","Small, non-combat drones are a common sight in the field. They’re fairly noisy but can fly about half a mile with good maneuverability before losing signal, relaying audio and visual information as they go."),
("Prosocollar","A collar-like device that fits snugly around its wearer’s neck, projecting a holographic image over their face and head. Prosocollars can change their wearer’s voice and scramble or change their appearance. The projection won’t stand up to close inspection, but it can easily fool electronic systems and distant observers."),
("Smart Scope","A powerful electronic scope that provides highresolution magnification up to two miles, and automatically adjusts its reticle for wind, gravity, and pressure. Smart scopes can project their field of vision and all data to the HUD of any networked user. They can also pair with other thermal, optical, or simulated-vision devices to further enhance targeting."),
("",""),
"""
# mech gear
create_weapontable = """CREATE TABLE IF NOT EXISTS Weapons(
                        description text,
                        size text,
                        type text,
                        affiliation text,
                        rankreq integer,
                        damage text,
                        damagetype text,
                        threat integer,
                        range integer,
                        cone integer,
                        burst integer,
                        line integer,
                        blast integer)"""

create_mechtable = """CREATE TABLE IF NOT EXISTS Mechs(
                      name text,
                      affiliation text,
                      role text,
                      size numeric,
                      armor integer,
                      save target integer,
                      sensors integer,
                      hp integer,
                      repaircap integer,
                      evasion integer,
                      speed integer,
                      edefense integer,
                      techattack integer,
                      sp integer,
                      heatcap integer,
                      traits text,
                      main integer,
                      flex integer,
                      heavy integer,
                      coresys text)"""

# tooltips
create_tooltips = """CREATE TABLE IF NOT EXISTS Tooltips(
                     terms text,
                     description text)"""


cursor.execute(create_weapontable)
cursor.execute(create_mechtable)
cursor.execute(create_tooltips)

load_tooltip = """INSERT INTO Tooltips(terms, description) VALUES
("Threat","Can Melee attack and OVERWATCH against targets within X spaces."),
("Range","Hits a target within X spaces."),
("Cone","Hits target in a cone X spaces long and X spaces wide."),
("Burst","Hits targets within X spaces of the acting character, including the space occupied by the acting character."),
("Line", "Hits every target in a line X spaces from the line's origin point."),
("Blast", "Hits targets from within X spaces of the Blast's origin (including the center)."),
("Kinetic","Deals damage through high-velocity impacts or massive blows."),
("Energy","Deals damage through lasers, bolts of electricity and blasting plasma."),
("Explosive","Deals damage through concussive waves and roaring explosions."),
("Heat","Adds points of HEAT to your mech instead of reducing HP, and ignores armor."),
("Burn","Deals immediate damage ignoring armor, and continues dealing damage at the end of the target's turns until they pass an ENGINEERING check.")
"""

cursor.execute(load_tooltip)
connection.commit()


# cursor.execute("""SELECT * FROM Tooltips""")
#
# print(cursor.fetchall())